### ISSUE TITLE
Put images inside folder

### ISSUE THREAD

**Issue by brunowego** [orangehill/jstree-bootstrap-theme#7]
I think will better if put images inside folders, not in the same directory of css.

**Comment by vedraan** [comment]
While this is something I usually also do on most of my projects, we will not be moving the images to a separate folder on this repo since we're aiming to preserve the same theme structure as the default jsTree theme.

Another problem with moving the files (images/fonts) is that not everyone has the same folder structure so it would be next to impossible to make everyone happy using relative or absolute URLs.

Also it's a very easy change for anyone who wants to change the image paths. All you need to do is to edit the style.css to find all the lines containing `url("` which point to image files and alter the path. There are just a few of those.
